### ISSUE TITLE
Do a release and publish as a nuget package

### ISSUE THREAD

**Issue by binki** [arogozine/EnumUtilities#2]
I know you said you’d be researching this in comments in #1, but I just wanted to have an issue around to track this for my own sake. Sorry for any [botherment](http://i.imgur.com/EYEcpvu.jpg).

I imagine you could roughly follow this sort of procedure:
1. Create/commit the necessary nuspec stuff and verify that `$ nuget pack` works.
2. Decide on the version number to use for release. Note [nuget versioning](https://docs.nuget.org/create/versioning) and the rationale of [semver](http://semver.org/). Update your nuspec with this version and commit.
3. Create a tag (e.g., `EnumUtilities-1.0.0`) for the release, push that to github, and publish that to nuget. Handle your InDev/master branches however you intend to handle that. (Is your intention that the master branch be “stable” and InDev be unstable?).

Thanks, looking forward to the package! ;-)

**Comment by arogozine** [comment]
Well my knowledge of git, github, and nuget increased from this.

Initial release is available here,
https://www.nuget.org/packages/EnumUtilities/1.0.0

**Comment by binki** [comment]
Thanks! Looks like that works.

If I may make one more request, didn’t catch this earlier. But the project I’d like you use EnumUtilities in targets .net-4.5.2 while EnumUtilities targets .net-4.6 (and we will eventually move to .net-4.6—but verifying that all the machines it gets installed on are compatible is a pain we “recently” went through so we’d like to wait a while (at least a few months) longer before doing that process again). EnumUtilities seems to compile and run its tests fine against .net-4.5 but breaks against .net-4.6. Would you consider retargeting your projects to .net-4.5 and making a new release and publishing the new release to nuget so that more people (or just I ;-)) can actually use it?

Thanks.

**Comment by binki** [comment]
Well, I’ve opened #5 for my lingering request, so this is done :-).
